# ~/.config/starship.toml

format = """\
[â”\\[î®™ ](#7eb8da)$username\
[ from ï„ˆ ](#7eb8da)$hostname\
[\\]](#7eb8da)$time$memory_usage$battery$cmd_duration
[â”£](#7eb8da)$directory$git_branch
[â”—â”â–º](#7eb8da) \
"""

# Use custom format
add_newline = true

[status]
symbol = 'ğŸ”´ '
success_symbol = ""
format = '[\[$symbol$status\]]($style)'
map_symbol = true
disabled = false

# â”€â”€â”€ PROMPT SYMBOL â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[character]
success_symbol = "[#](yellow)"
error_symbol = "[âœ˜](bold red)"

# â”€â”€â”€ TIME â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[time]
style = "#7eb8da"
disabled = false
format = "[\\[]($style)[$time]($style)[\\]]($style)"
time_format = "%y/%m/%d@%H:%M:%S"

# â”€â”€â”€ USER / HOST â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[username]
show_always = true
format = "[$user](#7eb8da)"

[hostname]
ssh_only = false
format = "[$hostname](#73b8da)"

# â”€â”€â”€ BATTERY â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[battery]
full_symbol = "ï‰€ "
charging_symbol = "îˆ¯ "
discharging_symbol = "ï‰„ "
format = "[\\[]($style)[${symbol}${percentage}]($style)[\\]]($style)"

[[battery.display]]
threshold = 30
style = "#FF5722"

[[battery.display]]
threshold = 100
style = "#6dfb72"

# â”€â”€â”€ EXECUTION TIME â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[cmd_duration]
min_time = 1
show_milliseconds = true
format = "[\\[]($style)[â± $duration]($style)[\\]]($style)"
style = "#BE9DDF"

# â”€â”€â”€ PATH â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[directory]
truncation_length = 8
fish_style_pwd_dir_length = 2
format = "[\\[](#FFA5D8)[ï» $path](#FFA5D8)[\\]](#FFA5D8)"

# â”€â”€â”€ GIT â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[git_branch]
ignore_branches = ["main", "master"]
format = "[\\[](#FFA5D8)[ïˆ î‚ $branch â‰¡](#FFA5D8)[\\]](#FFA5D8)"

[memory_usage]
threshold = 1
disabled = false
format = "[\\[]($style)[î‰¦ RAM:${ram}]($style)[\\]]($style)"
style = "#BE9DDF"

